<!-- Start Carousel -->
<div id="carouserIndex" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
            <li data-target="#carouserIndex" data-slide-to="0" class="active"></li>
            <li data-target="#carouserIndex" data-slide-to="1"></li>
            <li data-target="#carouserIndex" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img class="d-block img-fluid" src="<?php echo $this->basePath('img/1200x400-nothing.jpg') ?>" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <h3>Título</h3>
                    <p>Sub-título</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="<?php echo $this->basePath('img/1200x400-nothing.jpg') ?>" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="<?php echo $this->basePath('img/1200x400-nothing.jpg') ?>" alt="Third slide">
            </div>
      </div>
      <a class="carousel-control-prev" href="#carouserIndex" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouserIndex" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
      </a>
</div>
<!-- End Carousel -->
<!-- start Items -->
<br />
<div class="alert alert-info alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    Vacantes disponibles: <strong> <?php echo $this->vacantes->getNbResults() ?></strong>
</div>
<?php foreach ($this->vacantes as $vacante) :?>
    <div class="card text-center">
        <div class="card">
            <h3 class="card-header">
                <?php echo $vacante->getVacanteNombre(); ?>
            </h3>
            <div class="card-block">
                <h4 class="card-title"><?php echo $vacante->getSucursal()->getSucursalNombre() ?></h4>
                <p class="card-text"><?php echo $vacante->getVacanteHorario() ?></p>
                <p class="card-text"><?php echo "$" . number_format($vacante->getVacanteSueldo()) . " " . $vacante->getVacanteSueldoTipoPago() ?></p>
                <a href="<?php echo $this->url('vacantes', array('action'=>'vacante', 'id' => $vacante->getVacanteId()));?>" class="btn btn-primary">Ver detalles</a>
            </div>
        </div>
        <div class="card-footer text-muted">
            <?php echo "Publicado el: " . date('d-m-Y H:i:s', strtotime($vacante->getVacanteFechaInicia())) ?>
        </div>
    </div>
    <br />
<?php endforeach; ?>
<!-- End Items -->
<!-- Start Paginate -->
<?php if($this->vacantes->haveToPaginate()): ?>
    <nav aria-label="...">
        <ul class="pagination justify-content-center">
            <?php if ($this->vacantes->isFirstPage() == false): ?>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url('inicio', array('action'=>'index', 'id' => $this->vacantes->getFirstPage()));?>">Primera</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url('inicio', array('action'=>'index', 'id' => $this->vacantes->getPreviousPage()));?>">Anterior</a>
                </li>
            <?php endif; ?>
            <?php for($i=1; $i <= $this->vacantes->getLastPage(); $i++): ?>
                <?php if ($this->vacantes->getPage() == $i) :?>
                    <li class="page-item active">
                        <span class="page-link"><?php echo $i ?><span class="sr-only">(current)</span>
                        </span>
                    </li>
                <?php else: ?>
                    <li class="page-item"><a class="page-link" href="<?php echo $this->url('inicio', array('action'=>'index', 'id' => $i));?>"><?php echo $i ?></a></li>
                <?php endif; ?>

            <?php endfor; ?>
            <?php if ($this->vacantes->isLastPage() == false): ?>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url('inicio', array('action'=>'index', 'id' => $this->vacantes->getNextPage()));?>">Sigiente</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url('inicio', array('action'=>'index', 'id' => $this->vacantes->getLastPage()));?>">Última</a>
                </li>
            <?php endif; ?>

        </ul>
    </nav>
<?php endif; ?>
<!-- End Paginate -->