<br />
<br />
<div class="card text-center">
    <div class="card">
        <h3 class="card-header">
            <?php echo $vacante['vacante_nombre']; ?>
        </h3>
        <div class="card-block">
            <h4 class="card-title"><?php echo $vacante['vacante_sucursal']; ?></h4>
            <p class="card-text"><?php echo $vacante['vacante_horario'] ?></p>
            <p class="card-text"><?php echo "$" . number_format($vacante['vacante_sueldo']) . " " . $vacante['vacante_sueldo_tipo_pago'] ?></p>
            <p class="card-text"><?php echo $vacante['vacante_descripcion'] ?></p>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Postularme</button>
            <!-- Modal -->
            <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="ModalPostularme" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="ModalPostularme">Postularme para <strong><?php echo $vacante['vacante_nombre']; ?></strong></h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <?php $postulanteForm->prepare(); echo $this->form()->openTag($postulanteForm); ?>
                        <div class="modal-body">
                            <div id="form" class="form-group">
                                <div class="form-group">
                                    <?php echo $this->formRow($postulanteForm->get('vacante_id')->setValue($this->id)); ?>
                                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                        <div class="input-group-addon">@</div>
                                        <?php echo $this->formRow($postulanteForm->get('postulante_correo')); ?>
                                    </div>
                                    <br />
                                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                        <div class="input-group-addon"><i class="fa fa-user-o fa-lg" aria-hidden="true"></i></div>
                                        <?php echo $this->formRow($postulanteForm->get('postulante_nombre_completo')); ?>
                                    </div>
                                    <br />
                                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                        <div class="input-group-addon"><i class="fa fa-phone fa-lg" aria-hidden="true"></i></div>
                                        <?php echo $this->formRow($postulanteForm->get('postulante_telefono')); ?>
                                    </div>
                                    <br />
                                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                        <div class="input-group-addon"><i class="fa fa-link fa-lg" aria-hidden="true"></i></div>
                                        <?php echo $this->formRow($postulanteForm->get('postulante_enlace')); ?>
                                    </div>
                                    <br />
                                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                        <div class="input-group-addon"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i></div>
                                        <?php echo $this->formRow($postulanteForm->get('postulante_mensaje')); ?>
                                    </div>
                                    <br />
                                    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                        <div class="input-group-addon"><i class="fa fa-file-text-o fa-lg" aria-hidden="true"></i></div>
                                        <?php echo $this->formFile($postulanteForm->get('postulante_curriculum_vitae')); ?>
                                    </div>
                                    <?php // echo $this->formCollection($postulanteForm); ?>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <div class="input-group mb-2 mr-sm-2 mb-sm-0">
                                <span class="input-group-addon">
                                    <!--<input id="postulante_enviar_copia" name="postulante_enviar_copia" type="checkbox" aria-label="Checkbox for following text input">-->
                                    <?php echo $this->formCheckbox($postulanteForm->get('postulante_enviar_copia')); ?>
                                </span>
                                <span class="input-group-addon">Enviar copia a mi correo.</span>
                            </div>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                            <?php echo $this->formRow($postulanteForm->get('submit')); ?>
                        </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer text-muted">
        <?php echo "Publicado el: " . date('d-m-Y H:i:s', strtotime($vacante['vacante_fecha_inicia'])); ?>
    </div>
</div>
<br />
<!-- End Items -->
<script type="text/javascript">
    function postularme() {
        if ($('#form').hasClass('hidden-lg-up')){
            $('#form').removeClass('hidden-lg-up')
        }
    }

    // Eventos focusout
    $("#postulante_correo").focusout(function() {
        if ($("#postulante_correo").val().length > 0) {
            if($("#postulante_correo").hasClass('alert') == true){
                $("input#postulante_correo").removeClass('alert alert-danger');
            }
        }
    });

    $("#postulante_nombre_completo").focusout(function() {
        if ($("#postulante_nombre_completo").val().length > 0) {
            if($("#postulante_nombre_completo").hasClass('alert') == true){
                $("input#postulante_nombre_completo").removeClass('alert alert-danger');
            }
        }
    });

    $("#postulante_telefono").focusout(function() {
        if ($("#postulante_telefono").val().length > 0) {
            if($("#postulante_telefono").hasClass('alert') == true){
                $("input#postulante_telefono").removeClass('alert alert-danger');
            }
        }
    });

    $("#postulante_mensaje").focusout(function() {
        if ($("#postulante_mensaje").val().length > 0) {
            if($("#postulante_mensaje").hasClass('alert') == true){
                $("textarea#postulante_mensaje").removeClass('alert alert-danger');
            }
        }
    });

    $("#postulante_curriculum_vitae").focusout(function() {
        if ($("#postulante_curriculum_vitae").val().length > 0) {
            if($("#postulante_curriculum_vitae").hasClass('alert') == true){
                $("input#postulante_curriculum_vitae").removeClass('alert alert-danger');
            }
        }
    });

    // Al dar clic en botón Postularme
    $("#guardarPostulante").click(function() {
        var formElement = document.forms.namedItem("postulanteForm");
        var formData = new FormData(formElement);
        $.ajax({
            type: "POST",
            url: "<?php $this->url('vacantes', array('action'=>'vacante', 'id' => $this->id));?>",
            dataType : 'json',
            processData: false,
            contentType: false,
            enctype: 'multipart/form-data',
            data: formData,
            jsonpCallback: 'callback',
            success: function(data) {
                if (data.errorForm){
                    $.each( data.errorForm, function( keys, values ) {
                        $.each( values, function( key, value ) {
                            if(key == "postulante_correo"){
                                if (value != null){
                                    $("input#postulante_correo").addClass('alert alert-danger').attr('placeholder', value)
                                }else{
                                    $("input#postulante_correo").removeClass('alert alert-danger')
                                }
                            }
                            if(key == "postulante_nombre_completo"){
                                if (value != null){
                                    $("input#postulante_nombre_completo").addClass('alert alert-danger').attr('placeholder', value)
                                }else{
                                    $("input#postulante_nombre_completo").removeClass('alert alert-danger')
                                }
                            }
                            if(key == "postulante_telefono"){
                                if (value != null){
                                    $("input#postulante_telefono").addClass('alert alert-danger').attr('placeholder', value)
                                }else{
                                    $("input#postulante_telefono").removeClass('alert alert-danger')
                                }
                            }
                            if(key == "postulante_mensaje"){
                                if (value != null){
                                    $("textarea#postulante_mensaje").addClass('alert alert-danger').attr('placeholder', value)
                                }else{
                                    $("textarea#postulante_mensaje").removeClass('alert alert-danger')
                                }
                            }
                            if(key == "postulante_curriculum_vitae"){
                                if (value != null){
                                    $("input#postulante_curriculum_vitae").addClass('alert alert-danger').attr('placeholder', value)
                                }else{
                                    $("input#postulante_curriculum_vitae").removeClass('alert alert-danger')
                                }
                            }
                        })
                    })
                }
                if(data.error){
                    $.each( data.error, function( key, value ) {
                        if(key == "postulante_curriculum_vitae"){
                            if (value != null){
                                $("input#postulante_curriculum_vitae").addClass('alert alert-danger');
                                if($('#alertForm_cv').length > 0){
                                    if($('#alertForm_cv').length <= 0){
                                        $('div').remove('#alertForm_cv');
                                        $('#form').append('<div id="alertForm_cv" class="alert alert-danger" role="alert">'+value+'</div>');
                                    }
                                }else{
                                    $('#form').append('<div id="alertForm_cv" class="alert alert-danger" role="alert">'+value+'</div>');
                                }

                            }else{
                                $("input#postulante_curriculum_vitae").removeClass('alert alert-danger')
                            }
                        }
                    })
                }
                if(data.success){
                    $('#form').remove();
                    $('.modal-body').prepend('<div id="alertForm_exito" class="alert alert-success" role="success">Gracias por tu interés. Nos pondremos en contacto contigo lo mas pronto posible.</div>');
                    $('div').remove('.input-group');
                    $('input').remove('#guardarPostulante');
                }
            },
            error: function(){
                $('#form').prepend('<div class="alert alert-danger" role="alert">Error al intentar enviar tu postulación. Favor de intentar mas tarde.</div>');
            }
        });
        return false;
    });
</script>