<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <!--<meta charset="ISO-8859-1">-->
        <?php echo $this->headTitle('iJobs');?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/app.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.css'))?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.1.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        <script src="https://use.fontawesome.com/a04a00d5b9.js"></script>
    </head>
    <body>
        <div class="container">
            <nav class="navbar navbar-inverse navbar-light" style="background-color: rgb(224,226,229)">
                <div class="container">
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link text-muted" href="<?php echo $this->url('index') ?>"><?php echo $this->translate(' ') ?></a>
                            </li>
                        </ul>
                    <span>
                        <a class="nav-link" href="<?php echo $this->url('panel-login'); ?>">
                            <?php echo $this->translate('Iniciar sesión'); ?>
                        </a>
                    </span>
                    </div>
                </div>
            </nav>
            <nav class="navbar navbar-inverse navbar-light" style="background-color: #e3f2fd;">
                <div class="navbar-header">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('index') ?>"><img src="<?php echo $this->basePath('img/logo-100x100.png') ?>" alt="iJobs"/></a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link text-muted" href="<?php echo $this->url('vacantes') ?>"><?php echo $this->translate('Bolsa de trabajo') ?></a>
                        </li>
                    </ul>
                    <!--
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Buscar empleo">
                        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Buscar</button>
                    </form>
                    -->
                </div>
            </nav>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2012 - <?php echo date('Y') ?> por iJobs. <?php echo $this->translate('Todos los derechos reservados.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php $this->inlineScript()->appendScript('$(".carousel").carousel({
            interval: 3000
        })') ?>
    </body>
</html>
