<!-- Inicio Carousel -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img class="d-block img-fluid" src="<?php echo $this->basePath('/img/img-sliders/slider_1.jpg') ?>" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h3>...</h3>
                <p>...</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="<?php echo $this->basePath('/img/img-sliders/slider_2.jpg') ?>" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
                <h3>...</h3>
                <p>...</p>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="<?php echo $this->basePath('/img/img-sliders/slider_3.jpg') ?>" alt="Third slide">
            <div class="carousel-caption d-none d-md-block">
                <h3>...</h3>
                <p>...</p>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<!-- Fin Carousel -->
<!-- Inicio Form Vacantes -->
<div class="container my-2">
    <div class="row">
        <div class="col-12 col-sm-3">
            <label>Área:</label>
            <select id="vacante_area" class="form-control">
                <option value="">Selecciona una área</option>
                <?php foreach($this->areas_laborales as $arealaboralKey => $arealaboralValor): ?>
                    <option value="<?php echo $arealaboralValor['arealaboral_clave']; ?>"><?php echo $arealaboralValor['arealaboral_nombre']; ?></option>';
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-12 col-sm-3">
            <label>Estado:</label>
            <select id="vacante_lugar" class="form-control">
                <option value="">Selecciona un estado</option>
                <?php foreach($this->estados as $estadoKey => $estadoValor): ?>
                    <option value="<?php echo $estadoValor['sepomex_idestado']; ?>"><?php echo $estadoValor['sepomex_estado']; ?></option>';
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-12 col-sm-3">
            <label>Puesto/empresa:</label>
            <input id="vacante_clave" type="text" class="form-control" >
        </div>
        <div class="col-12 col-sm-3" style="margin-top: 2rem">
            <button type="submit" class="btn btn-primary"><i class="fa fa-search mr-2" aria-hidden="true"></i>Buscar</button>
        </div>
    </div>
</div>
<hr />
<!-- Fin Form Vacantes -->
<!-- Inicio Pasos Crear Perfil -->
<div class="container my-5">
    <div class="mb-5 text-center">
        <h2>Postularte a una vacante es muy fácil con iJobs</h2>
        <p>Crea tu perfil para que puedas postularte a las vacantes que sean de tu interés</p>
    </div>
    <div class="row">
        <div class="col">
            <div class="card text-center" style="width: 18rem;">
                <div class="my-2">
                    <p class="card-text">Paso 1</p>
                </div>
                <div class="mt-1 text-center text-warning">
                    <i class="fa fa-file-text-o fa-5x" aria-hidden="true"></i>
                </div>
                <div class="card-block">
                    <h4 class="card-title">Crea una cuenta</h4>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-center" style="width: 18rem;">
                <div class="my-2">
                    <p class="card-text">Paso 2</p>
                </div>
                <div class="mt-1 text-center text-info">
                    <i class="fa fa-id-card-o fa-5x" aria-hidden="true"></i>
                </div>
                <div class="card-block">
                    <h4 class="card-title">Sube tu CV</h4>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-center" style="width: 18rem;">
                <div class="my-2">
                    <p class="card-text">Paso 3</p>
                </div>
                <div class="mt-1 text-success">
                    <i class="fa fa-user-plus fa-5x" aria-hidden="true"></i>
                </div>
                <div class="card-block">
                    <h4 class="card-title">Postulate</h4>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fin Pasos Crear Perfil -->
<!-- Inicio Empresas -->
<div class="bg-faded py-5">
    <div class="container">
        <div class="mb-5 text-center">
            <h2>Clientes que han obtenido grandes beneficios con nosotros</h2>
            <p>Vacantes activas por empresa</p>
        </div>
        <div class="row">
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
            <div class="col">
                <i class="fa fa-apple fa-5x" aria-hidden="true"></i>
            </div>
        </div>
    </div>
</div>
<!-- Fin Empresas -->