<?php $this->headTitle("Registrarme | iJobs"); ?>
<div class="container my-5">
    <div class="row text-center">
        <div class="col-12 col-md-6 offset-lg-1 col-lg-4">
            <div class="card">
                <div style="height: 30px"></div>
                <i class="fa fa-user-circle-o fa-5x" aria-hidden="true"></i>
                <div class="card-block">
                    <h4 class="card-title">Postulante</h4>
                    <p class="card-text">Registrate y sube tu CV, podrás obtener el empleo de tus sueños.</p>
                    <a href="<?php echo $this->url('website-registrarme/postulante') ?>"><div class="btn btn-primary">Registrarme</div></a>
                </div>
            </div>
        </div>
        <div class="mt-3 mt-md-0 col-12 col-md-6 offset-lg-2 col-lg-4 offset-lg-1">
            <div class="card">
                <div style="height: 30px"></div>
                <i class="fa fa-university fa-5x" aria-hidden="true"></i>
                <div class="card-block">
                    <h4 class="card-title">Empresa</h4>
                    <p class="card-text">Registra tu empresa y comienza a postular vacantes.</p>
                    <a href="<?php echo $this->url('website-registrarme/empresa') ?>"><div class="btn btn-primary">Registrarme</div></a>
                </div>
            </div>
        </div>
    </div>
</div>