<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <!--<meta charset="ISO-8859-1">-->
        <?php echo $this->headTitle('iJobs');?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('css/website.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.css'))?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.1.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <!-- reCaptcha Google -->
        <script src='https://www.google.com/recaptcha/api.js'></script>
    </head>
    <body>
        <div class="container text-right">
            <a href="<?php echo $this->url('website-registrarme') ?>" class="btn btn-primary btn-sm" role="button" aria-disabled="true"><i class="fa fa-pencil" aria-hidden="true"></i>&nbsp;&nbsp;Registrarme</a>
            <a href="#" class="btn btn-success btn-sm" role="button" aria-disabled="true"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;&nbsp;Iniciar Sesión</a>
        </div>
        <nav class="navbar navbar-toggleable-sm navbar-light bg-faded">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="<?php echo $this->basePath('/img/img-navbar/ijob-logo.png') ?>" width="40" height="40" alt="iJobs">
                </a>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo $this->url('website-inicio') ?>">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo $this->url('website-vacantes') ?>">Vacantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo $this->url('website-registrarme/postulante') ?>">Subir CV</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo $this->url('website-registrarme/empresa') ?>">Publicar Vacante</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <?php echo $this->content; ?>
        <footer>
            <div class="row bg-inverse text-center text-muted">
                <div class="p-4 col-12 offset-sm-2 col-sm-4">
                    <h3>Contacto</h3>
                    <br />
                    <p>contacto@ijobs.com</p>
                </div>
                <div class="p-4 col-12 col-sm-4">
                    <h3>Redes Sociales</h3>
                    <br />
                    <a class="cursor-pointer m-3" href="#"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a>
                    <a class="cursor-pointer" href="#"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></a>
                </div>
                <div class="col-12 bg-primary text-white">
                    <p class="pt-3">&copy; <?php echo date('Y') ?> por iJobs. <?php echo $this->translate('Todos los derechos reservados.') ?></p>
                </div>
            </div>
        </footer>
    </body>
</html>
